include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - Unity/**
    - android/unityLibrary/**

linter:
  rules:
    avoid_print: false  
    curly_braces_in_flow_control_structures: false
    constant_identifier_names: false
