name: talk2statue
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.6 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  flutter_bloc: ^8.1.5
  get: ^4.6.6
  equatable: ^2.0.5
  google_fonts: ^6.1.0
  either_dart: ^0.3.0
  file_picker: ^6.1.1
  just_audio: ^0.9.36
  path_provider: ^2.1.2
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.9.0
  google_sign_in: ^6.2.1
  dots_indicator: ^3.0.0
  flutter_spinkit: ^5.2.0
  awesome_dialog: ^3.2.0
  flutter_screenutil: ^5.9.0
  image_picker: ^1.0.7
  conditional_builder_null_safety: ^0.0.6
  http: ^1.2.0
  record: ^5.0.4
  avatar_glow: ^3.0.1
  shared_preferences: ^2.2.2
  flutter_native_splash: ^2.4.0
  data_repository: 
    path: packages/data_repository
  models_repository: 
    path: packages/models_repository
  authentication_repository: 
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository
  flutter_unity_widget: ^2022.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  
flutter_launcher_icons:
  image_path: "assets/logo.png"
  android: true
  ios: false
  
flutter_native_splash:
  # dart run flutter_native_splash:create
  # dart run flutter_native_splash:remove

  color: "#F6D880"
  color_dark: "#F6D880"
  image: assets/logo_splash.png
  image_dark: assets/logo_splash.png

  android_12:
    color: "#F6D880"
    color_dark: "#F6D880"
    image: assets/logo_splash.png
    image_dark: assets/logo_splash.png
    
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
